{'405nm power-lightPower': 0.0,
 '488nm power-lightPower': 0.4,
 '561nm power-lightPower': 0.0,
 '647nm power-lightPower': 0.0,
 'Show Window ': False,
 'Show Window Camera views': True,
 'Show Window Camera views    (236, 45): 506': True,
 'Show Window Camera views    (8, 203): 2230': True,
 'Show Window Logging panels': True,
 'Show Window Macro Stage': True,
 'Show Window Mosaic view': True,
 'Show Window PyShell': True,
 'Show Window SIM intensity profile': False,
 'Show Window Touch Screen view': False,
 'Show Window linkam settings': False,
 'WindowPositions': {'': (0, 0),
                     'Camera views': (2112, 308),
                     'Cockpit': (160, 221),
                     'Logging panels': (1204, 103),
                     'Macro Stage': (75, 75),
                     'Mosaic view': (275, 275),
                     'PyShell': (978, 440),
                     'SIM intensity profile': (150, 150),
                     'Touch Screen view': (125, 125)},
 'camera:reflected_SETTINGS': {'Fan mode': 'off', 'TemperatureSetPoint': -80},
 'camera:transmitted_SETTINGS': {'Fan mode': 'off', 'TemperatureSetPoint': -80},
 'experimentAltitudes': [],
 'mosaicScaleBar': 0,
 'mosaicTileOverlap': 0.0,
 'reflected filter_SETTINGS': None,
 'savedBottom': 3000.0,
 'savedTop': 3010.0,
 'transmitted filter_SETTINGS': None}